### ISSUE TITLE
Xiaomi mi desk lamp

### ISSUE THREAD

**Issue by EXTRAMINER** [stanvx/Home-Assistant-Configuration#1]
Hi
I have a Xiaomi mi desk lamp, and i see you have one too.
I don't know how to set-up them in Home Assistant. Can you help me?

Thank you very much

**Comment by elmexdechileen** [comment]
Hi,

Set-up is pretty easy. As for the home assistant config, you only have to
add the light the same way as I did in my configuration (only way I could
find the ip was via my router).

Just don't forget to turn on the api access in the yeelight app on your
phone. I forgot to so this initially and it wouldnt work with this enabled.

Good luck, let me know if it works!

Max

**Comment by EXTRAMINER** [comment]
Ok thank you

**Comment by EXTRAMINER** [comment]
- @elmexdechileen Can I use the xiaomi ceiling lamp (https://m.gearbest.com/ceiling-lights/pp_596249.html?wid=89&lkid=12220464) with the same, or other components in home assistant?
Thanks

**Comment by stanvx** [comment]
Hi, It looks like that ceiling lamp may be supported within Home Assistant, see the thread below. Did you manage to get your Desk Lamp setup?
https://community.home-assistant.io/t/yeelight-led-ceiling-light-compatible-with-ha/29509/27

**Comment by EXTRAMINER** [comment]
Ok, so maybe for the next week I'll take it. I will keep you informed.
The Xiaomi Desk Lamp should come to me this week, I'll write to you if I have problems.


Thank you very much.
Livio Avalle

**Comment by wiuwiu** [comment]
Hi @livioavalle. Did you configure your Xiaomi mi desk lamp with HA? If so, could you post your config? Which component did you use? MQTT Light? I want to order this lamp but only if I will sure that this lamp can be manageable by HA.
