### ISSUE TITLE
Harmony Activity MDI Icon isn't updating when activity is changed.

### ISSUE THREAD

**Issue by stanvx** [stanvx/Home-Assistant-Configuration#4]
https://github.com/stanvx/Home-Assistant-Configuration/blob/master/packages/harmony_tv_control.yaml#L35-L48

**Comment by askusbloodfist** [comment]
Thought i could send you how i did to solved what you tried to do.
So what i did in general was to make another sensor that was checking the activity sensors changes then made it change its icons acordingly. 

  - platform: template
    sensors:
      harmony_activity:
        friendly_name: 'Harmony Aktivitet'
        value_template: '{{ states.remote.vardagsrum.attributes.current_activity }}'
      harmonyicon:
        friendly_name: 'Harmony Aktivitet'
        value_template: "{{ states('sensor.harmony_activity') }}"
        icon_template: >
          {% if is_state('sensor.harmony_activity', 'Htpc') %}
            mdi:kodi
          {% elif is_state('sensor.harmony_activity', 'Apple Tv') %}
            mdi:apple
          {% elif is_state('sensor.harmony_activity', 'Tv') %}
            mdi:television-guide
          {% elif is_state('sensor.harmony_activity', 'Raspberry Pi') %}
            mdi:raspberrypi
          {% else %}
            mdi:television
          {% endif %}

**Comment by stanvx** [comment]
Thanks so much @askusbloodfist ! in my case I was able to keep the icon_template within the harmony_activity but rather than calling the remote's activity i called the sensor itself! Works perfectly.
https://github.com/stanvx/Home-Assistant-Configuration/blob/master/packages/harmony_tv_control.yaml#L35-L48
